### ISSUE TITLE
.jshintrc file ignored

### ISSUE THREAD

**Issue by centaurreader** [asednev/JSLint.VS#2]
I've got my .jshintrc file in /scripts/ in my solution but those options don't seem to have any effect. Is there some other configuration I'm missing? Thanks.

**Comment by centaurreader** [comment]
I guess the workaround is to "override linter options" at the solution level then specifying your requirements for the solution in the generated XML. No need for .jshintrc at all.

**Comment by asednev** [comment]
@centaurreader you're right, .jshintrc isn't used by this extension. It works off the configuration in XML file.
