### ISSUE TITLE
Ignore jQuery.js (and other files)

### ISSUE THREAD

**Issue by Montago** [asednev/JSLint.VS#4]
It would be awesome to make a list of files to ignore ... jQuery and similar plugins generate TONS of JSHint warnings that i don't care about.

**Comment by asednev** [comment]
@Montago, there is already an option to ignore files or folders. Right click on the file or folder and select "Skip on build". In case of jQuery & plugins, you may find it easier to put them in a folder and ignore that folder.

![image](https://cloud.githubusercontent.com/assets/3236025/10586325/72fa7d76-7650-11e5-9257-4dca5125e3c8.png)
